### ISSUE TITLE
Please update gem version to make new locale param available on the render method

### ISSUE THREAD

**Issue by jakeonrails** [sendwithus/sendwithus_ruby#42]

**Comment by demoore** [comment]
hey @jakeonrails there should be a new version in a couple of days

**Comment by demoore** [comment]
Done!

**Comment by jakeonrails** [comment]
Hey @demoore! Sorry to keep bothering you about this one :)

I'm not sure what's going on, but I updated to 1.10.1 and when I open the source code for the gem locally it does not contain the new code for the render API method to support locales.

I have no idea how that's possible, because the master branch here shows 1.10.1 as the version, and the render method with locale support is here, but not when I download the gem through rubygems. Strange!

**Comment by jakeonrails** [comment]
there's no rush on getting this fixed - I just need to remember to switch my gem over to my fork every time I run that email templates script we're working on, or else it renders the English versions and nobody wants to see those! :dancer:

**Comment by demoore** [comment]
I have no idea how that happened :stuck_out_tongue: but I rebuilt the gem, cracked it open to make sure the correct was in place, and pushed it again. Upgrade to 1.10.2, it should be good to go now!

**Comment by jakeonrails** [comment]
Sweet Thanks Dylan! I updated it and the method is there now! :)
