### ISSUE TITLE
Remove customer from group method signature

### ISSUE THREAD

**Issue by evanmarks** [sendwithus/sendwithus_ruby#50]
It looks like this method is missing the arguments in its definition:

```
def customer_remove_from_group()
  endpoint = "customers/#{email_address})/groups/#{group_id}"
  SendWithUs::ApiRequest.new(@configuration).delete(endpoint)
end
```

There is also an extra ')' right after the email_address interpolation

**Comment by bvanvugt** [comment]
@evanmarks thanks for bringing this up - we're trying to sort out internally how this made it into master at all...

We'll get a fix out in the next day or two.

**Comment by evanmarks** [comment]
@bvanvugt Thanks!  I'm integrating with your gem right now for the first time and have run into one other pain point so far, so I thought I'd let you all know.

A common pattern for us is to create our user and put them in a group right after they sign up on our site.  I see the API can handle settings groups in the create customer call, but that isn't possible in the gem.  Back-to-back create then add to group calls don't work because the add to group call fails thinking the user doesn't exist.  Would be great to just allow those initial groups in the create customer method.

Also, I notice that if make requests for a customer that doesn't exists, it returns an instance of SendWithUs::ApiBadRequest.  It would be great to have a specific error message for this so I don't have to go parsing the error message text.  There are cases where I might want to unsubscribe a user and rescue the not found error, but do care about other classes of errors.

Cheers

**Comment by evanmarks** [comment]
Looks like this method is not implemented - obj.drip_unsubscribe('customer@example.com')

**Comment by mariesta** [comment]
It seems there is a typo in our docs. It should be drips_unsubscribe(email). Thanks for pointing it out. :)

**Comment by mariesta** [comment]
Fixed. :)

**Comment by evanmarks** [comment]
Thanks
