### ISSUE TITLE
UTF-8 in email address causes an error: "incompatible character encodings..."

### ISSUE THREAD

**Issue by maxkwallace** [sendwithus/sendwithus_ruby#60]
I have a user in my database with non-ASCII characters in their email address. According to http://stackoverflow.com/a/37320735/1067145 this is valid per RFC 6531.

However, I'm encountering an error when attempting to push this user to sendwithus as a customer:

```
irb(main):035:0> SendWithUsClient.get.customer_create(User.find(id).email, { foo: 'bar' })
Encoding::CompatibilityError: incompatible character encodings: ASCII-8BIT and UTF-8
	from /app/vendor/bundle/ruby/2.3.0/gems/send_with_us-1.12.0/lib/send_with_us/api_request.rb:61:in `request'
	from /app/vendor/bundle/ruby/2.3.0/gems/send_with_us-1.12.0/lib/send_with_us/api_request.rb:18:in `post'
	from /app/vendor/bundle/ruby/2.3.0/gems/send_with_us-1.12.0/lib/send_with_us/api.rb:260:in `customer_create'
	from (irb):35
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.1/lib/rails/commands/console.rb:110:in `start'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.1/lib/rails/commands/console.rb:9:in `start'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:68:in `console'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /app/vendor/bundle/ruby/2.3.0/gems/railties-4.2.5.1/lib/rails/commands.rb:17:in `<top (required)>'
	from /app/bin/rails:9:in `require'
	from /app/bin/rails:9:in `<main>'
```

Here's some more detail about the address:

```
irb(main):039:0> email.valid_encoding?
=> true
irb(main):040:0> email.encoding
=> #<Encoding:UTF-8>
```

The only non-ASCII character it contains is http://unicode.scarfboy.com/?s=2006.

**Comment by maxkwallace** [comment]
Hey Dylan,

Thanks for the follow-up!

- If sendwithus doesn't support non-ASCII email addresses in any form, you
should add that to your docs somewhere (I looked-- maybe I missed it?)
- Are there any plans to add support? (It's okay if this is a "no"-- just
want to have an idea.)

If sendwithus doesn't support non-ASCII email addresses then I think it's
correct to have the Ruby client Gem throw an exception (much better than
failing silently). The only change I'd ask for is that you throw a
SendWithUs::Error or a subclass of it.

**Comment by demoore** [comment]
Great points — we should mention the lack of non-ASCII support somewhere. I'm curious, where would you look first? We have a few places I could put that information 😸 

Our team is keeping a close eye on the state of IDN email address support across ESPs, but right now they're inconsistently supported. We'll update once it makes sense to do so.

**Comment by maxkwallace** [comment]
My first reaction is to Google "sendwithus ascii email support" or somthing
similar to that.

Then, to search https://support.sendwithus.com/ for "ascii" or "unicode",
something like that.

Third, to Ctrl-F on the API docs: https://www.sendwithus.com/docs/api


Looking at https://support.sendwithus.com/, there isn't an obvious place to
put it. I would suggest putting it in the API docs, but unfortunately, the
search at https://support.sendwithus.com/ doesn't search the API docs as
well as the FAQ articles. I'm in the habit of checking both, so either
would work...

**Comment by demoore** [comment]
Thanks @maxkwallace that's super helpful 😃 We'll get that added to the API docs and support pages.

**Comment by moxuz** [comment]
@maxkwallace I have pushed a fix to make sure a proper exception is returned!

**Comment by maxkwallace** [comment]
@moxuz Thanks!
