### ISSUE TITLE
Batch requests?

### ISSUE THREAD

**Issue by 9mm** [sendwithus/sendwithus_ruby#67]
Hey, I'd love to use batch endpoint with this gem, is that supported?

**Comment by FlipCodes** [comment]
Hey @9mm,

I believe you also submitted a ticket to support [at] sendwithus [dot] com for this issue, so I'm going to close the issue for now. :)
---
For anyone else who's wondering, the Sendwithus Ruby client does not currently support the batch endpoint. This is something we'd like to add support for in the future. We do accept PR's!

**Comment by 9mm** [comment]
Cool thanks
