### ISSUE TITLE
Can't set version_name when calling render template 

### ISSUE THREAD

**Issue by creativej** [sendwithus/sendwithus_ruby#70]
Looks like [Render template](https://github.com/sendwithus/sendwithus_ruby/blob/master/lib/send_with_us/api.rb#L154) doesn't support `version_name` argument like the [HTTP API](https://www.sendwithus.com/docs/api#rendering-templates) does. 

The PHP client seems to have got it correct. 
https://github.com/sendwithus/sendwithus_php#render-templates

**Comment by demoore** [comment]
Hey @creativej we've kept `version_name` around for the render API endpoint for legacy reasons. Version IDs are the safer choice — a version's ID won't change but names are editable.

**Comment by creativej** [comment]
icic. So is `version_name` deprecating? 
I can see `version_name` to be useful for rendering all of locale versions without the need to find out all the version_id from each locale of a template.
I agree that version ids are safer though.

**Comment by demoore** [comment]
Yeah, we'll be removing version name eventually.

That's also a great point, I could see that being useful when having to test a large number of versions across multiple locales. Currently, if you specify a locale but not a version ID Sendwithus will render the _published_ version. If you wanted to test non-published versions then you would need to specify the version id.

**Comment by creativej** [comment]
> If you wanted to test non-published versions then you would need to specify the version id.
Yes exactly which can be a pain because one would have to update the test after each language is translated for a template. Also just to gather the version_id of all the different languages (we have 7 locales) is slow and tedious.

I hope your team would revisit the decision.
