### ISSUE TITLE
UTF-8 payloads that raise a 400 BadRequest cause a nested error due to incomptible encoding coercion

### ISSUE THREAD

**Issue by jordanambra** [sendwithus/sendwithus_ruby#78]
### Client version
4.0.1 but the offending code is in 4.1.0+ as well

Here is the line number: https://github.com/sendwithus/sendwithus_ruby/blob/v4.1.0/lib/send_with_us/api_request.rb#L61

### Expected behaviour
I should receive a SendWithUs::ApiBadRequest exception

### Actual behaviour
I receive Encoding::CompatibilityError: incompatible character encodings: ASCII-8BIT and UTF-8

### Steps to reproduce
The easiest way to reproduce this is to attempt to send an email to an invalid email address with UTF-8 encoded characters that cannot be coerced to ASCII. For example, just send an email to `Ö`.

**Comment by dylan-swu** [comment]
Hey @jordanambra thanks for pointing that out. I have a PR, here #79 , that should fix the issue. Can you take a look?

**Comment by jordanambra** [comment]
That seems good to me, as long as it's OK for you to coerce to UTF-8. Most people use UTF-8 so I don't think it would be a widespread problem.

**Comment by dylan-swu** [comment]
Agreed. Thanks again for bringing this to our attention @jordanambra. There's a new version (4.1.1) up on RubyGems with the fix in place.
