### ISSUE TITLE
function get_events missing

### ISSUE THREAD

**Issue by seven-ex** [sendwithus/sendwithus_ruby#81]
In the **Ruby** version, the query is missing from the log events.

PHP Version:
` public function get_events($log_id) {
        $endpoint = "logs/" . $log_id . "/events";
        return $this->api_request($endpoint, self::HTTP_GET);
    }`

can you implement that?

**Comment by demoore** [comment]
Hey @seven-ex this should be out in the latest release (v4.2.0). Why are you trying to retrieve log events? There might be a better way than using our ruby client.

**Comment by seven-ex** [comment]
@demoore I need the log last update date.
