### ISSUE TITLE
Add get drip deactivate method

### ISSUE THREAD

**Issue by seven-ex** [sendwithus/sendwithus_ruby#83]
function remove_from_all_drip_campaigns missing 

In the Ruby version, the query is missing from the drip_campaigns deactivate POST.
In the PHP Version exists.

can you implement that?

**Comment by demoore** [comment]
@seven-ex it looks like that's implemented here: https://github.com/sendwithus/sendwithus_ruby#remove-customer-from-drip-campaign

It looks like we just need to make the documentation clearer.
