### ISSUE TITLE
How to do parallel requests?

### ISSUE THREAD

**Issue by amilner42** [sendwithus/sendwithus_ruby#84]
This is a question, not a feature-request.

I'm just curious the expected way to send multiple requests to SendWithUs at once with this gem. It takes like 0.5 second to send a single email (if waiting on the http request response) so sending large amounts of emails in a blocking sync way is not ideal.

Thanks!

**Comment by demoore** [comment]
This is pretty dependent on use case, scale, and stack so we don't have a recommended way to do this.

If this is a quick and dirty job then I wouldn't use this gem. I would instead use something like this [async request library to issue requests](https://github.com/socketry/async-http#multiple-requests).

If I needed something more scalable then I would use a queuing system with workers taking jobs off of the queue and then sending an email. This way I could dynamically scale queues and workers depending on the amount of email that needed to get sent.

**Comment by amilner42** [comment]
Thanks for your advice!
